#!/bin/bash

### Luc Kadletz 2020 ###

# Get ready to rock
sudo apt-get update
sudo apt-get install software-properties-common apt-transport-https wget cowsay fortune curl

## Get keys
# Actual apt-get install commands are commented out, we add to TARGETS & do them all at once at the end
TARGETS=""

cowsay -f duck "Hi! I'm the Install Duck. Let's get those keys so we know who to trust!"

# Spotify Music 
curl -sS https://download.spotify.com/debian/pubkey.gpg | sudo apt-key add - 
echo "deb http://repository.spotify.com stable non-free" | sudo tee /etc/apt/sources.list.d/spotify.list
TARGETS="$TARGETS spotify-client" 
cowsay -f duck "Got spotify repo!"
# sudo apt-get install spotify-client

# Steam Games
# sudo tee /etc/apt/sources.list.d/steam.list <<'EOF'
# deb [arch=amd64,i386] http://repo.steampowered.com/steam/ precise steam
# deb-src [arch=amd64,i386] http://repo.steampowered.com/steam/ precise steam
# EOF
# sudo dpkg --add-architecture i386
# TARGETS="$TARGETS libgl1-mesa-dri:amd64 libgl1-mesa-dri:i386 libgl1-mesa-glx:amd64 libgl1-mesa-glx:i386 steam-launcher"
# cowsay -f duck "Got steam configured!"
# sudo apt-get install libgl1-mesa-dri:amd64 libgl1-mesa-dri:i386 libgl1-mesa-glx:amd64 libgl1-mesa-glx:i386 steam-launcher

# Discord Chat
sudo wget -qO /tmp/discord.deb "https://discordapp.com/api/download?platform=linux&format=deb"
TARGETS="$TARGETS /tmp/discord.deb"
cowsay -f duck "Got Discord package!"
# sudo apt install /tmp/discord.deb 

# Sublime Text / Merge
wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
TARGETS="$TARGETS sublime-text sublime-merge"
cowsay -f duck "Got Sublime repo!"
# sudo apt-get install sublime-text sublime-merge

# Visual Studio Code
wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
TARGETS="$TARGETS code"
cowsay -f duck "Got Visual studio code repo!"
# sudo apt install code

# Kvantum Theme Engine
# sudo apt install qt5-style-kvantum qt5-style-kvantum-themes
TARGETS="$TARGETS qt5-style-kvantum qt5-style-kvantum-themes"

# Install all packages
cowsay -f duck "Now we can simply apt install $TARGETS"
sudo apt update
sudo apt install $TARGETS

# TODO graphics card shit

fortune | cowsay -f duck
